"""Constants for the immich integration."""

DOMAIN = "immich"
MANUFACTURER = "Immich"
CONF_WATCHED_ALBUMS = "watched_albums"
CONF_FAVORITES = "favorite_album"
FAVORITE_IMAGE_ALBUM = "favorite_image"
FAVORITE_IMAGE_ALBUM_NAME = "Random favorite image"

ALBUM_REFRESH_INTERVAL = 720

SETTING_INTERVAL_OPTION_NONE = "Never"
SETTING_INTERVAL_OPTION_10 = "10 seconds"
SETTING_INTERVAL_OPTION_30 = "30 seconds"
SETTING_INTERVAL_OPTION_60 = "60 seconds"
SETTING_INTERVAL_OPTION_120 = "120 seconds"
SETTING_INTERVAL_OPTION_300 = "300 seconds"
SETTING_INTERVAL_OPTIONS = [
    SETTING_INTERVAL_OPTION_NONE,
    SETTING_INTERVAL_OPTION_10,
    SETTING_INTERVAL_OPTION_30,
    SETTING_INTERVAL_OPTION_60,
    SETTING_INTERVAL_OPTION_120,
    SETTING_INTERVAL_OPTION_300,
]
SETTING_INTERVAL_DEFAULT_OPTION = SETTING_INTERVAL_OPTION_60
SETTING_INTERVAL_MAP = dict(
    {
        SETTING_INTERVAL_OPTION_NONE: None,
        SETTING_INTERVAL_OPTION_10: 10,
        SETTING_INTERVAL_OPTION_30: 30,
        SETTING_INTERVAL_OPTION_60: 60,
        SETTING_INTERVAL_OPTION_120: 120,
        SETTING_INTERVAL_OPTION_300: 300,
    }
)
