"""Constants for the immich integration."""

DOMAIN = "immich"
MANUFACTURER = "Immich"
CONF_WATCHED_ALBUMS = "watched_albums"
CONF_FAVORITES = "favorite_album"
CONF_WATCHED_PERSONS = "watched_persons"

FAVORITE_IMAGE_ALBUM = "favorite_image"
FAVORITE_IMAGE_ALBUM_NAME = "Random favorite image"
RANDOM_IMAGE_ALBUM = "random_image"
RANDOM_IMAGE_ALBUM_NAME = "Random image"

ALBUM_REFRESH_INTERVAL = 720

SETTING_INTERVAL_OPTION_NONE = "Never"
SETTING_INTERVAL_OPTION_5 = "5 seconds"
SETTING_INTERVAL_OPTION_10 = "10 seconds"
SETTING_INTERVAL_OPTION_30 = "30 seconds"
SETTING_INTERVAL_OPTION_60 = "60 seconds"
SETTING_INTERVAL_OPTION_120 = "120 seconds"
SETTING_INTERVAL_OPTION_300 = "300 seconds"
SETTING_INTERVAL_OPTIONS = [
    SETTING_INTERVAL_OPTION_NONE,
    SETTING_INTERVAL_OPTION_5,
    SETTING_INTERVAL_OPTION_10,
    SETTING_INTERVAL_OPTION_30,
    SETTING_INTERVAL_OPTION_60,
    SETTING_INTERVAL_OPTION_120,
    SETTING_INTERVAL_OPTION_300,
]
SETTING_INTERVAL_DEFAULT_OPTION = SETTING_INTERVAL_OPTION_60
SETTING_INTERVAL_MAP = dict(
    {
        SETTING_INTERVAL_OPTION_NONE: None,
        SETTING_INTERVAL_OPTION_5: 5,
        SETTING_INTERVAL_OPTION_10: 10,
        SETTING_INTERVAL_OPTION_30: 30,
        SETTING_INTERVAL_OPTION_60: 60,
        SETTING_INTERVAL_OPTION_120: 120,
        SETTING_INTERVAL_OPTION_300: 300,
    }
)

SETTING_THUMBNAILS_MODE_ORIGINAL = "Original Only"
SETTING_THUMBNAILS_MODE_THUMBNAIL = "JPEG Thumbnail"
SETTING_THUMBNAILS_MODE_THUMBNAIL_BACKUP = "JPEG Thumbnail as backup"
SETTING_THUMBNAILS_MODE_OPTIONS = [
    SETTING_THUMBNAILS_MODE_ORIGINAL,
    SETTING_THUMBNAILS_MODE_THUMBNAIL,
    SETTING_THUMBNAILS_MODE_THUMBNAIL_BACKUP,
]
SETTING_THUMBNAILS_MODE_DEFAULT = SETTING_THUMBNAILS_MODE_THUMBNAIL

SETTING_ORIENTATION_PORTRAIT = "Portrait"
SETTING_ORIENTATION_LANDSCAPE = "Landscape"
SETTING_ORIENTATION_MIXED = "Mixed"
SETTING_ORIENTATION_OPTIONS = [
    SETTING_ORIENTATION_PORTRAIT,
    SETTING_ORIENTATION_LANDSCAPE,
    SETTING_ORIENTATION_MIXED
]
SETTING_ORIENTATION_DEFAULT = SETTING_ORIENTATION_MIXED